name: boilerplate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: any
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.8
  cached_network_image: ^2.5.1
  fluttertoast: ^7.0.1+1
  auto_route: ^0.6.7
  http_interceptor: ^1.0.2
  mask_text_input_formatter: ^1.0.7
  flutter_modular: ^2.0.0+1
  toast: ^0.1.5
  flutter_styled_toast: ^1.3.2
  autocomplete_textfield: ^1.7.3
  permission_handler: ^5.0.1+1
  dio: ^5.0.3
  flutter_date_pickers: ^0.4.1
  universal_html: ^1.2.3
  load: ^0.1.6
  simple_search_bar: ^0.1.7
  flappy_search_bar: ^1.7.2
  dropdown_search: ^0.4.4
  search_choices: ^1.0.17
  firebase_messaging: ^9.0.0-1.0.nullsafety.2
  onesignal_flutter: ^2.6.0
  google_sign_in: ^4.5.1
  firebase_auth: ^0.21.0-1.1.nullsafety.3
  http: ^0.13.5
  flutter_circle_color_picker: ^0.2.0
  uuid: ^2.2.0
  cloud_firestore: ^0.17.0-1.0.nullsafety.2
  pull_to_refresh: ^1.6.1
  firebase_storage: ^8.0.0-1.0.nullsafety.1
  file_picker: ^1.13.3
  url_launcher: ^5.5.0
  firebase_core: ^0.8.0-1.0.nullsafety.2
  photo_view: ^0.10.1
  flutter_downloader: ^1.5.0
  path_provider: ^1.6.28
  wakelock: ^0.1.4+2
  
  # permission_handler: 4.4.0



  # file_picker: ^1.13.3
  # file_picker_web: ^1.0.2+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
